spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spvms_db
    username: spvms_user
    password: strong_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  springdoc.api-docs.path: /api-docs
  springdoc.swagger-ui.path: /swagger-ui.html
  spring.show-actuator: true

server:
  port: 8080
